name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build, Push, and Release a Docker container to Heroku
        uses: gonuit/heroku-docker-deploy@v1.3.3 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "nobullrecipes" # what you named the app when you made it in heroku
          heroku_email: "Seth.dow@gmail.com"
